name = "Caplog.txt"
license = "MIT"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "A simple plaintext based logging format that will last for centuries"

homepage = "https://github.com/h-enk/doks-child-theme"
demosite = "https://doks-child-theme.netlify.app"

tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]

[author]
  name = "Henk Verlinde"
  homepage = "https://henkverlinde.com"
